// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductTracking.API.Data;

#nullable disable

namespace ProductTracking.API.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductTracking.API.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "f73c5a92-6459-4288-b253-79a42045f9b5",
                            Brand = "Company-ABC0",
                            Color = 2,
                            Name = "Name-3",
                            Size = 46
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "6a086e8b-1b64-460b-aba3-8553e8b2ebf4",
                            Brand = "Company-ABC9",
                            Color = 3,
                            Name = "Name-8",
                            Size = 18
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "7ff295ae-2672-4d00-a56a-207aaf461853",
                            Brand = "Company-ABC1",
                            Color = 3,
                            Name = "Name-8",
                            Size = 66
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "c967f617-a8bf-44a0-99c1-4e81fdab990c",
                            Brand = "Company-ABC8",
                            Color = 4,
                            Name = "Name-9",
                            Size = 63
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "3ab22062-d885-40d4-8fd4-469ec83fecf3",
                            Brand = "Company-ABC2",
                            Color = 9,
                            Name = "Name-8",
                            Size = 67
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "a2a3ba67-0ba5-4c63-a222-69e39965565b",
                            Brand = "Company-ABC7",
                            Color = 8,
                            Name = "Name-6",
                            Size = 72
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "f71a83b8-45c6-42ab-bb98-e7be6ead1533",
                            Brand = "Company-ABC6",
                            Color = 9,
                            Name = "Name-1",
                            Size = 94
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "082c80e4-7e76-4fbe-bb97-c0936de44921",
                            Brand = "Company-ABC7",
                            Color = 1,
                            Name = "Name-7",
                            Size = 70
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "43ad2da8-8038-4652-b02b-420294d17cee",
                            Brand = "Company-ABC7",
                            Color = 1,
                            Name = "Name-7",
                            Size = 70
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "0c4e9550-e92d-4f47-860e-447f03bf9245",
                            Brand = "Company-ABC2",
                            Color = 8,
                            Name = "Name-1",
                            Size = 30
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "ea4a1294-518a-4487-9fdc-dd1f41f4f07e",
                            Brand = "Company-ABC3",
                            Color = 4,
                            Name = "Name-6",
                            Size = 20
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "718503ca-bdb8-4885-85fd-9c8fc349a5fc",
                            Brand = "Company-ABC4",
                            Color = 8,
                            Name = "Name-6",
                            Size = 28
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "9ad283b3-15be-4e78-b972-8873287ee243",
                            Brand = "Company-ABC1",
                            Color = 5,
                            Name = "Name-1",
                            Size = 79
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "634f2514-1f5c-46cd-af22-a813043dae91",
                            Brand = "Company-ABC4",
                            Color = 1,
                            Name = "Name-9",
                            Size = 92
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "f10ad16a-b60c-4dd9-99d6-239220b1cfcf",
                            Brand = "Company-ABC9",
                            Color = 9,
                            Name = "Name-2",
                            Size = 29
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "e5faef0f-3c07-43a6-8427-c0889b808a8f",
                            Brand = "Company-ABC5",
                            Color = 8,
                            Name = "Name-2",
                            Size = 46
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "b395d97f-2c98-4acc-a52f-9e14e3fee5b2",
                            Brand = "Company-ABC4",
                            Color = 10,
                            Name = "Name-5",
                            Size = 71
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "868c9638-5969-483e-869d-32982923f8ec",
                            Brand = "Company-ABC2",
                            Color = 3,
                            Name = "Name-5",
                            Size = 13
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "a1d9be7e-5273-4196-bd18-270c118c7a04",
                            Brand = "Company-ABC6",
                            Color = 5,
                            Name = "Name-0",
                            Size = 59
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "ec701963-1238-4bf1-91af-fbca77428786",
                            Brand = "Company-ABC1",
                            Color = 6,
                            Name = "Name-1",
                            Size = 47
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "4aa20a11-47f3-4578-abab-2b57e3cbe7ef",
                            Brand = "Company-ABC5",
                            Color = 6,
                            Name = "Name-5",
                            Size = 12
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "abb259c7-310e-45f0-ae91-f4496f31ca96",
                            Brand = "Company-ABC1",
                            Color = 2,
                            Name = "Name-5",
                            Size = 36
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "a4f432bc-13bb-4b1a-9638-4c03bf998e15",
                            Brand = "Company-ABC8",
                            Color = 8,
                            Name = "Name-1",
                            Size = 36
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "12d3099b-bfac-4d82-9e77-3d5c7161a115",
                            Brand = "Company-ABC9",
                            Color = 7,
                            Name = "Name-8",
                            Size = 35
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "729d0226-fb73-40f9-ac85-8badcb695b6c",
                            Brand = "Company-ABC0",
                            Color = 2,
                            Name = "Name-4",
                            Size = 45
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "2d6a66d8-9564-4f6f-a452-5f7bf113175a",
                            Brand = "Company-ABC4",
                            Color = 8,
                            Name = "Name-3",
                            Size = 28
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "f0fe4a48-bea8-4281-ab39-27aaabb34550",
                            Brand = "Company-ABC7",
                            Color = 8,
                            Name = "Name-4",
                            Size = 20
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "494c32cb-b89c-482f-a07c-6f561b3c369a",
                            Brand = "Company-ABC4",
                            Color = 3,
                            Name = "Name-1",
                            Size = 88
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "29cf94b5-f0e9-46ed-af1c-495c011f35de",
                            Brand = "Company-ABC0",
                            Color = 1,
                            Name = "Name-6",
                            Size = 47
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "275c585b-37bc-4668-828c-300d46fe33ed",
                            Brand = "Company-ABC4",
                            Color = 3,
                            Name = "Name-4",
                            Size = 61
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "6da04f05-e79a-4834-a90c-3b97054b9ec1",
                            Brand = "Company-ABC6",
                            Color = 1,
                            Name = "Name-5",
                            Size = 19
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "b53581a5-4637-4d23-af4d-955ea224adb6",
                            Brand = "Company-ABC7",
                            Color = 3,
                            Name = "Name-1",
                            Size = 20
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "d3f11e5f-cca6-46d7-955c-4ecf3bef8add",
                            Brand = "Company-ABC3",
                            Color = 10,
                            Name = "Name-9",
                            Size = 20
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "dc29bec9-fb79-4907-affd-f6f18b4b4255",
                            Brand = "Company-ABC5",
                            Color = 10,
                            Name = "Name-3",
                            Size = 68
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "2099bc72-5a4a-4806-a79f-8284840998e5",
                            Brand = "Company-ABC6",
                            Color = 4,
                            Name = "Name-6",
                            Size = 63
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "1d80fe69-c0c1-4044-94d4-e7d0da926aa8",
                            Brand = "Company-ABC6",
                            Color = 6,
                            Name = "Name-8",
                            Size = 64
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "6e31a4a5-2b9f-49ee-9b58-6a738aedecf8",
                            Brand = "Company-ABC8",
                            Color = 2,
                            Name = "Name-7",
                            Size = 65
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "8c23fe9c-819f-4e4f-97f3-4539d7dde98b",
                            Brand = "Company-ABC1",
                            Color = 10,
                            Name = "Name-5",
                            Size = 68
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "8f3dcfca-d530-4d5d-95f5-aefddac5ca88",
                            Brand = "Company-ABC5",
                            Color = 3,
                            Name = "Name-4",
                            Size = 21
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "fb3c4ebd-c5f0-488e-a566-d82a310a5a2a",
                            Brand = "Company-ABC1",
                            Color = 5,
                            Name = "Name-7",
                            Size = 10
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "1adfb1c3-0b83-4135-9ad9-730acc31a24b",
                            Brand = "Company-ABC7",
                            Color = 10,
                            Name = "Name-4",
                            Size = 36
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "578ff1bb-177f-4e6d-9c78-f78bc2afc9b0",
                            Brand = "Company-ABC7",
                            Color = 3,
                            Name = "Name-3",
                            Size = 32
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "1741a70f-d355-4298-b5b8-2848f2f3f1f8",
                            Brand = "Company-ABC7",
                            Color = 10,
                            Name = "Name-8",
                            Size = 32
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "a75d2459-fdd6-4b96-81e1-94769e7f203f",
                            Brand = "Company-ABC7",
                            Color = 9,
                            Name = "Name-7",
                            Size = 30
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "90dc377c-0d51-494c-aa9e-1bf002794830",
                            Brand = "Company-ABC3",
                            Color = 6,
                            Name = "Name-8",
                            Size = 84
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "3f220da8-2caa-478c-9318-c0559b4e5c05",
                            Brand = "Company-ABC0",
                            Color = 8,
                            Name = "Name-6",
                            Size = 53
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "6049522d-e016-471d-9a9d-0403dbf935c6",
                            Brand = "Company-ABC7",
                            Color = 4,
                            Name = "Name-0",
                            Size = 26
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "e1367fb8-224c-4304-a0f6-00bd5434da69",
                            Brand = "Company-ABC2",
                            Color = 1,
                            Name = "Name-1",
                            Size = 47
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "09262dd7-0664-494c-b5a7-b1efa1c0c7ed",
                            Brand = "Company-ABC7",
                            Color = 8,
                            Name = "Name-5",
                            Size = 21
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "4c6020b8-ae48-41b7-b25f-e7e18aa17b66",
                            Brand = "Company-ABC4",
                            Color = 10,
                            Name = "Name-4",
                            Size = 97
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "58074334-8771-4698-a387-bf6aac94e2a9",
                            Brand = "Company-ABC9",
                            Color = 4,
                            Name = "Name-8",
                            Size = 23
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "86447a35-028c-4acb-bf68-4b0b69c8291a",
                            Brand = "Company-ABC2",
                            Color = 2,
                            Name = "Name-1",
                            Size = 94
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "c9efd372-e166-4b9d-8f43-0620315a9e0e",
                            Brand = "Company-ABC2",
                            Color = 1,
                            Name = "Name-1",
                            Size = 39
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "e5bf6e12-2db4-4d58-be89-6899152062a9",
                            Brand = "Company-ABC5",
                            Color = 3,
                            Name = "Name-8",
                            Size = 76
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "315c672b-b112-4a88-b9d8-f6c823794ffd",
                            Brand = "Company-ABC9",
                            Color = 4,
                            Name = "Name-3",
                            Size = 66
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "bb050d10-85fc-4374-ba25-69dd67b0101d",
                            Brand = "Company-ABC1",
                            Color = 8,
                            Name = "Name-4",
                            Size = 81
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "2f884739-c6ea-4150-aa00-99bd049c4186",
                            Brand = "Company-ABC0",
                            Color = 6,
                            Name = "Name-9",
                            Size = 56
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "ec8e93f1-24fa-4025-827b-c9e68c631037",
                            Brand = "Company-ABC9",
                            Color = 3,
                            Name = "Name-9",
                            Size = 69
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "d8c5c509-e4fd-4e10-9021-c2f569530b00",
                            Brand = "Company-ABC0",
                            Color = 5,
                            Name = "Name-2",
                            Size = 37
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "28471429-a5f2-4d27-8a45-be8662beee03",
                            Brand = "Company-ABC4",
                            Color = 7,
                            Name = "Name-2",
                            Size = 80
                        },
                        new
                        {
                            Id = 61,
                            Barcode = "678578a9-675d-4ad5-89fd-dda6c0fbafe0",
                            Brand = "Company-ABC9",
                            Color = 6,
                            Name = "Name-2",
                            Size = 17
                        },
                        new
                        {
                            Id = 62,
                            Barcode = "0271d20f-4fc7-41ca-b8fc-d1440e695e9b",
                            Brand = "Company-ABC3",
                            Color = 10,
                            Name = "Name-7",
                            Size = 79
                        },
                        new
                        {
                            Id = 63,
                            Barcode = "0aa7630c-b719-4a79-b4be-9671b6b9369d",
                            Brand = "Company-ABC9",
                            Color = 8,
                            Name = "Name-3",
                            Size = 99
                        },
                        new
                        {
                            Id = 64,
                            Barcode = "d5fbc2bb-01cd-4ed9-8ef7-427e92c5db4c",
                            Brand = "Company-ABC6",
                            Color = 1,
                            Name = "Name-1",
                            Size = 97
                        },
                        new
                        {
                            Id = 65,
                            Barcode = "726da87d-fdd4-4aa7-8c60-873acfeb861a",
                            Brand = "Company-ABC0",
                            Color = 7,
                            Name = "Name-0",
                            Size = 83
                        },
                        new
                        {
                            Id = 66,
                            Barcode = "16dc2621-779b-46b4-a0e4-18f83874590c",
                            Brand = "Company-ABC9",
                            Color = 10,
                            Name = "Name-9",
                            Size = 23
                        },
                        new
                        {
                            Id = 67,
                            Barcode = "9234a492-0682-4df8-9af8-e157e67d62d7",
                            Brand = "Company-ABC0",
                            Color = 5,
                            Name = "Name-0",
                            Size = 45
                        },
                        new
                        {
                            Id = 68,
                            Barcode = "d21f8eeb-bf6c-4bd9-976b-f0ab943381c2",
                            Brand = "Company-ABC9",
                            Color = 7,
                            Name = "Name-4",
                            Size = 84
                        },
                        new
                        {
                            Id = 69,
                            Barcode = "a5496673-d941-4f82-9226-d3a947f3e01d",
                            Brand = "Company-ABC3",
                            Color = 3,
                            Name = "Name-1",
                            Size = 88
                        },
                        new
                        {
                            Id = 70,
                            Barcode = "1808fe64-bcdd-44af-933a-d041dab25bd8",
                            Brand = "Company-ABC5",
                            Color = 8,
                            Name = "Name-5",
                            Size = 83
                        },
                        new
                        {
                            Id = 71,
                            Barcode = "061b9fc4-1508-4281-bff9-6f09512c5275",
                            Brand = "Company-ABC4",
                            Color = 5,
                            Name = "Name-0",
                            Size = 15
                        },
                        new
                        {
                            Id = 72,
                            Barcode = "df76bf4a-fb3c-4054-856b-11fc00feeb48",
                            Brand = "Company-ABC5",
                            Color = 5,
                            Name = "Name-0",
                            Size = 24
                        },
                        new
                        {
                            Id = 73,
                            Barcode = "a1f63a4a-15cd-4c24-a9f9-9ed1d731287a",
                            Brand = "Company-ABC4",
                            Color = 7,
                            Name = "Name-3",
                            Size = 17
                        },
                        new
                        {
                            Id = 74,
                            Barcode = "b9090a17-b517-45bd-86ca-c9081d9afbd6",
                            Brand = "Company-ABC1",
                            Color = 1,
                            Name = "Name-8",
                            Size = 51
                        },
                        new
                        {
                            Id = 75,
                            Barcode = "7a239713-3d53-4802-b317-75627b17212e",
                            Brand = "Company-ABC9",
                            Color = 8,
                            Name = "Name-7",
                            Size = 53
                        },
                        new
                        {
                            Id = 76,
                            Barcode = "0e1b1780-d12e-4144-97b2-a4e34f588993",
                            Brand = "Company-ABC9",
                            Color = 7,
                            Name = "Name-9",
                            Size = 30
                        },
                        new
                        {
                            Id = 77,
                            Barcode = "ae818371-f9ea-4961-83c8-f13dc1a92df1",
                            Brand = "Company-ABC9",
                            Color = 8,
                            Name = "Name-5",
                            Size = 56
                        },
                        new
                        {
                            Id = 78,
                            Barcode = "ebb56799-005c-4aeb-95a9-29434b4d5f64",
                            Brand = "Company-ABC8",
                            Color = 10,
                            Name = "Name-7",
                            Size = 76
                        },
                        new
                        {
                            Id = 79,
                            Barcode = "09e8ce1a-28c8-4ae1-a67b-e49bb54a3e81",
                            Brand = "Company-ABC0",
                            Color = 8,
                            Name = "Name-9",
                            Size = 79
                        },
                        new
                        {
                            Id = 80,
                            Barcode = "c1c159f6-5c5c-41fc-af4a-5652ec30374e",
                            Brand = "Company-ABC5",
                            Color = 10,
                            Name = "Name-2",
                            Size = 42
                        },
                        new
                        {
                            Id = 81,
                            Barcode = "9854938e-635f-4d0e-a9f4-12807a3490c7",
                            Brand = "Company-ABC5",
                            Color = 7,
                            Name = "Name-7",
                            Size = 36
                        },
                        new
                        {
                            Id = 82,
                            Barcode = "8aad33c0-d016-49bb-8fac-f06bac84ed09",
                            Brand = "Company-ABC7",
                            Color = 8,
                            Name = "Name-0",
                            Size = 70
                        },
                        new
                        {
                            Id = 83,
                            Barcode = "bf31caa0-1a10-4645-8c7e-15d31bac48f0",
                            Brand = "Company-ABC6",
                            Color = 2,
                            Name = "Name-2",
                            Size = 99
                        },
                        new
                        {
                            Id = 84,
                            Barcode = "abfb31d6-e21c-4231-adc6-7c60f4133bd6",
                            Brand = "Company-ABC2",
                            Color = 7,
                            Name = "Name-4",
                            Size = 58
                        },
                        new
                        {
                            Id = 85,
                            Barcode = "8542f3ad-33d2-462a-a524-53797292ddc1",
                            Brand = "Company-ABC1",
                            Color = 3,
                            Name = "Name-8",
                            Size = 66
                        },
                        new
                        {
                            Id = 86,
                            Barcode = "e3a7be42-ca78-422f-acf9-3405c6915491",
                            Brand = "Company-ABC5",
                            Color = 8,
                            Name = "Name-0",
                            Size = 13
                        },
                        new
                        {
                            Id = 87,
                            Barcode = "4187d3bb-6c30-46a6-a953-096c00338348",
                            Brand = "Company-ABC9",
                            Color = 3,
                            Name = "Name-3",
                            Size = 89
                        },
                        new
                        {
                            Id = 88,
                            Barcode = "2f85a518-db53-4386-9b7a-6166e8c488db",
                            Brand = "Company-ABC0",
                            Color = 6,
                            Name = "Name-0",
                            Size = 90
                        },
                        new
                        {
                            Id = 89,
                            Barcode = "581217b0-e4e0-4439-a399-6730134cd3c5",
                            Brand = "Company-ABC3",
                            Color = 9,
                            Name = "Name-6",
                            Size = 63
                        },
                        new
                        {
                            Id = 90,
                            Barcode = "de4c1857-e770-4e26-bcb1-766665b69447",
                            Brand = "Company-ABC6",
                            Color = 3,
                            Name = "Name-4",
                            Size = 62
                        },
                        new
                        {
                            Id = 91,
                            Barcode = "fe41a6ce-801f-4827-8cb6-93dd0a2f2a54",
                            Brand = "Company-ABC9",
                            Color = 5,
                            Name = "Name-2",
                            Size = 68
                        },
                        new
                        {
                            Id = 92,
                            Barcode = "cff6864b-624c-4efa-ad4d-6e3d61101566",
                            Brand = "Company-ABC6",
                            Color = 3,
                            Name = "Name-1",
                            Size = 79
                        },
                        new
                        {
                            Id = 93,
                            Barcode = "1991d7a5-4295-488e-9f24-bf493d2bb27a",
                            Brand = "Company-ABC0",
                            Color = 5,
                            Name = "Name-2",
                            Size = 31
                        },
                        new
                        {
                            Id = 94,
                            Barcode = "da7c3ba5-6595-49fb-855b-adfa8eea9b22",
                            Brand = "Company-ABC8",
                            Color = 1,
                            Name = "Name-2",
                            Size = 92
                        },
                        new
                        {
                            Id = 95,
                            Barcode = "34628679-9ce3-41fd-bc55-b7200199096a",
                            Brand = "Company-ABC4",
                            Color = 4,
                            Name = "Name-1",
                            Size = 17
                        },
                        new
                        {
                            Id = 96,
                            Barcode = "8e4417bb-2a05-45d8-83a0-82e21a26e1c6",
                            Brand = "Company-ABC6",
                            Color = 2,
                            Name = "Name-5",
                            Size = 83
                        },
                        new
                        {
                            Id = 97,
                            Barcode = "0c73ff10-555e-4948-8586-db71a5ce6a7f",
                            Brand = "Company-ABC5",
                            Color = 8,
                            Name = "Name-0",
                            Size = 30
                        },
                        new
                        {
                            Id = 98,
                            Barcode = "aac895fd-ab85-4528-aebb-4a3aac3456f9",
                            Brand = "Company-ABC2",
                            Color = 9,
                            Name = "Name-7",
                            Size = 18
                        },
                        new
                        {
                            Id = 99,
                            Barcode = "ddf1e2df-e4c8-407c-9d99-aef34c31506d",
                            Brand = "Company-ABC0",
                            Color = 1,
                            Name = "Name-8",
                            Size = 75
                        },
                        new
                        {
                            Id = 100,
                            Barcode = "a58f4ac3-742f-4aba-8f3c-b79929d23a20",
                            Brand = "Company-ABC7",
                            Color = 6,
                            Name = "Name-8",
                            Size = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
